import {StyleSheet, Platform, Dimensions} from 'react-native';

const marginHorizontal = 4;
const marginVertical = 4;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  Body: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  icons: {
    flex: 1,
    flexDirection: 'row',
    padding: 10,
    paddingBottom: 20,
  },
  iconsLeft: {
    flex: 0.5,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  FiltersIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconsRight: {
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  IconText: {
    color: '#333',
    marginBottom: 10,
    fontSize: 16,
  },
  FiltersView: {
    flex: 0.5,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  IconText1: {
    color: '#333',
    marginRight: 5,
    fontSize: 14,
    alignSelf: 'center',
  },
  text: {justifyContent: 'center', alignItems: 'center', fontSize: 25},
  DrawerIconTop: {marginLeft: 20, marginTop: 10},
  DrawerIconView: {justifyContent: 'flex-start'},
  ButtonsView: {
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 5,
  },
  dropdownView: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: Dimensions.get('window').width - 10,
    marginHorizontal: 10,
  },
  btnColorBlue: {
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 10,
    fontSize: 10,
    margin: 3,
    borderWidth: 2,
    borderColor: '#333333',
    flex: 1,
  },
  btnAddToCart: {
    alignItems: 'center',
    backgroundColor: '#333333',
    borderWidth: 2,
    borderColor: '#333333',
    padding: 10,
    margin: 3,
    flex: 1,
  },
  btnBuyNow: {
    alignItems: 'center',
    backgroundColor: '#DE041F',
    borderWidth: 2,
    borderColor: '#DE041F',
    padding: 8,
    margin: 3,
    flex: 1,
  },
  btnText2: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'Muli-SemiBold',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnText3: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopColor: '#ccc',
    borderTopWidth: 1,
    marginTop: 12,
    marginBottom: 10,
  },
  productDetail: {
    paddingHorizontal: 10,
    flex: 0.3,
    fontFamily: 'Muli-Bold',
    fontSize: 22,
  },
  txtProductDetails: {
    color: '#DE041F',
    fontSize: 20,
    fontFamily: 'Muli-Bold',
    textAlign: 'left',
  },
  txtProductRelevant: {
    color: '#DE041F',
    fontSize: 24,
    paddingTop: 15,
    fontFamily: 'Muli-Bold',
    textAlign: 'left',
    alignSelf: 'center',
  },
  txtProduct: {
    color: '#333333',
    fontSize: 14,
    fontFamily: 'Muli-Bold',
    textAlign: 'left',
    marginTop: 5,
    marginBottom: 5,
  },
  txtProduct1: {
    color: '#333333',
    fontSize: 12,
    textAlign: 'left',
    fontFamily: 'Muli-Regular',
    textAlign: 'justify',
    lineHeight: 30,
  },
  titleView: {
    flex: 1,
    width: '100%',
    backgroundColor: '#333',
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginVertical: 5,
  },
  titleText: {
    color: '#fe491a',
    fontSize: 14,
    letterSpacing: 2,
    fontFamily: 'Coyote-SemiBoldDEMO',
  },
  txtView: {
    flexDirection: 'row',
  },
  ImageMain: {
    alignItems: 'center',
    alignSelf: 'center',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  boxContainer: {
    marginTop: marginVertical,
    marginBottom: marginVertical + 25,
    marginLeft: marginHorizontal,
    marginRight: marginHorizontal,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  price: {
    color: '#333333',
    fontSize: 16,
    fontFamily: 'Muli-Bold',
    textAlign: 'left',
  },
  smPrice: {
    color: '#333',
    fontSize: 11,
    fontFamily: 'Muli-Bold',
    textAlign: 'left',
  },
  iconsPost: {
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 5,
  },
  singleProduct: {
    paddingLeft: 5,
  },
  iconsLeftProduct: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingLeft: 5,
  },
  iconsRight: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight: 10,
    marginLeft: 10,
  },
  iconsRightShare: {
    marginRight: 10,
  },
  IconTextProduct: {
    color: '#707374',
    fontSize: 9,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    fontFamily: 'Muli-Regular',
    width: '80%',
  },
  TextProductMain: {
    color: '#707374',
    fontSize: 11,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    fontFamily: 'Muli-SemiBold',
  },
  iconsRightHeart: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 5,
  },
  buttonOver: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 1,
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 4,
    padding: 10,
    backgroundColor: 'rgba(5,5,4,.6)',
    position: 'absolute',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 100,
  },
  buttonOver1: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 1,
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 4,
    padding: 12,
    backgroundColor: 'rgba(5,5,4,.7)',
    position: 'absolute',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 160,
  },
  btnText: {
    color: '#fff',
    fontSize: 10,
    letterSpacing: 2,
    fontFamily: 'Muli-Bold',
    textTransform: 'uppercase',
  },
});
