import {StyleSheet} from 'react-native';
const marginHorizontal = 4;
const marginVertical = 4;
export const styles = StyleSheet.create({
  button: {
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 1,
    padding: 10,
    backgroundColor: 'rgba(6,6,6,.8)',
    alignItems: 'center',
    alignSelf: 'center',
    marginHorizontal: 4,
    marginVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnText: {
    color: '#fff',
    fontSize: 10,
    letterSpacing: 2,
    fontFamily: 'Muli-Regular',
  },
  btnFilter1: {
    alignItems: 'center',
    backgroundColor: '#333',
    borderWidth: 2,
    borderRadius: 3,
    borderColor: '#333',
    paddingVertical: 0.5,
    paddingHorizontal: 5,
    marginRight: 3,
  },
  btnText4: {
    color: '#fe491a',
    fontSize: 11,
    fontFamily: 'Muli-SemiBold',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonOver: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 1,
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 4,
    padding: 10,
    backgroundColor: 'rgba(5,5,4,.6)',
    position: 'absolute',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 100,
  },
  ImageMain: {
    alignItems: 'center',
    alignSelf: 'center',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  boxContainer: {
    marginBottom: marginVertical,
    marginLeft: marginHorizontal,
    marginRight: marginHorizontal,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 50,
  },
  price: {
    color: '#333333',
    fontSize: 11,
    fontFamily: 'Muli-Bold',
    textAlign: 'left',
    paddingBottom: 2,
  },
  iconsPost: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'flex-start',
    paddingHorizontal: 5,
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderColor: '#ccc',
  },
  iconsLeftProduct: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  iconsRightHeart: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    flex: 0.5,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  twoIcons: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  twoIconsChildView: {
    flex: 0.5,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  twoIconsChildView1: {
    flex: 0.5,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  IconTextProduct: {
    color: '#707374',
    fontSize: 10,
    fontFamily: 'Muli-Regular',
  },
  prodbox: {
    marginVertical: 20,
  },
});
