import {StyleSheet, Platform, Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  container: {
    flex: 1,
    // paddingTop: Platform.OS === "android" ? 24 : 0,
    backgroundColor: '#fff',
    // paddingBottom: Platform.OS === "android" ? 10 : 0
  },
  menu: {
    flex: 1,
    flexDirection: 'row',
  },
  loginimgtext: {
    marginLeft: 15,
    marginVertical: 10,
  },
  loginText: {
    color: '#fff',
    fontFamily: 'lexio',
    margin: 10,
    fontSize: 16,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  view1: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 30,
    backgroundColor: '#333',
  },
  HeadView: {
    padding: 10,
    flexDirection: 'row',
    backgroundColor: '#333333',
  },
  DrawerIconTop: {
    marginLeft: 40,
    marginTop: 30,
    flex: 1,
  },
  logoimgbox: {
    flex: 1,
    flexDirection: 'row',
    marginLeft: 37,
    justifyContent: 'center',
    alignItems: 'center',
  },

  logoimg: {
    width: 150,
    height: 24,
  },

  letterView: {
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  barBtn: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  DrawerIconView: {
    marginTop: Platform.OS === 'android' ? 0 : 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    alignItems: 'center',
  },
  header: {
    height: 200,
  },
  Logo: {
    alignItems: 'center',
    width: 100,
    height: 100,
  },
  ImageLetters: {
    alignItems: 'center',
    width: '100%',
    height: 45,
    margin: 20,
    marginTop: 20,
  },
  avatar: {
    width: 130,
    height: 130,
    borderRadius: 63,
    borderWidth: 4,
    borderColor: 'white',
    marginBottom: 10,
    alignSelf: 'center',
    position: 'absolute',
    marginTop: 130,
    alignItems: 'center',
  },
  avatarView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: 130,
    height: 130,
    borderRadius: 63,
    borderWidth: 4,
    borderColor: '#fe491a',
    alignSelf: 'center',
    marginBottom: 10,
    marginTop: 130,
    position: 'absolute',
  },
  input: {
    width: Dimensions.get('window').width - 40,
    height: 40,
    borderBottomColor: '#333333',
    paddingTop: 5,
    margin: 2,
    alignItems: 'center',
    alignSelf: 'center',
    borderBottomWidth: 0.5,
    marginBottom: 10,
  },
  name: {
    fontFamily: 'lexio',
    fontSize: 22,
    color: '#333',
  },
  body: {
    marginTop: 40,
  },
  bodyContent: {
    flex: 1,
    marginTop: 30,
    padding: 20,
    alignItems:'center'
  },
  info: {
    fontSize: 16,
    color: '#fe491a',
    marginTop: 10,
  },
  description: {
    fontSize: 16,
    color: '#333',
    marginTop: 10,
    fontFamily: 'Muli-SemiBold',
  },
  btnView: {
    alignSelf: 'center',
    flexDirection: 'row',
    marginVertical: 20,
  },
  btnView1: {
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: 40,
  },
  buttonContainer: {
    marginHorizontal: 10,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 10,
    paddingHorizontal: 30,
    // borderRadius: 10,
    backgroundColor: '#333',
  },
  btnText: {
    fontSize: 14,
    fontFamily: 'Muli-Bold',
    color: '#fe491a',
  },
  passwordInput: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: Dimensions.get('window').width - 40,
  },
  action: {
    flexDirection: 'row',
    marginTop: 7,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    paddingBottom: 5,
  },
  actionError: {
    flexDirection: 'row',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FF0000',
    paddingBottom: 5,
    fontFamily: 'Muli-Regular',
  },
  textInput: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    borderBottomWidth: 0,
    marginBottom: -10,
    color: '#333',
    fontFamily: 'Muli-Regular',
  },
  errorMsg: {
    color: '#FF0000',
    fontSize: 14,
    fontFamily: 'Muli-Regular',
  },
});
